DELETE FROM [OLIST].dbo.[TB_ACT_CUSTOMER];
DELETE FROM [OLIST].dbo.[TB_ACT_GEOLOCATION];
DELETE FROM [OLIST].dbo.[TB_ACT_ORDER];
DELETE FROM [OLIST].dbo.[TB_ACT_ORDER_ITEMS];
DELETE FROM [OLIST].dbo.[TB_ACT_ORDER_PAYMENT];
DELETE FROM [OLIST].dbo.[TB_ACT_ORDER_REVIEW];
DELETE FROM [OLIST].dbo.[TB_ACT_PRODUCT];
DELETE FROM [OLIST].dbo.[TB_ACT_SELLER];