DROP DATABASE IF EXISTS OLIST;
GO
CREATE DATABASE OLIST;
GO

USE OLIST;

CREATE TABLE dbo.TB_ACT_GEOLOCATION (
	ZIP_CODE_PREFIX					INT,
	GEO_LAT							FLOAT,
	GEO_LNG							FLOAT,
	GEO_CITY						VARCHAR(70),
	GEO_STATE						CHAR(2)
);

CREATE TABLE dbo.TB_ACT_CUSTOMER (
	ID								VARCHAR(150),
	UNIQUE_ID						VARCHAR(150),
	ZIP_CODE_PREFIX					INT,
	CITY							VARCHAR(70),
	STATE							CHAR(2)
);

CREATE TABLE dbo.TB_ACT_SELLER (
	ID								VARCHAR(150),
	ZIP_CODE_PREFIX					INT,
	CITY							VARCHAR(70),
	STATE							CHAR(2)
);

CREATE TABLE dbo.TB_ACT_PRODUCT (
	ID								VARCHAR(150),
	CATEGORY_NAME					VARCHAR(100),
	WEIGHT_G						INT NULL,
	LENGTH_CM						INT NULL,
	HEIGHT_CM						INT NULL,
	WIDTH_CM						INT NULL
);

CREATE TABLE dbo.TB_ACT_ORDER (
	ID								VARCHAR(150),
	CUSTOMER						VARCHAR(150),
	STATUS							VARCHAR(40),
	PURCHASE_TIMESTAMP				DATETIME2,
	APPROVED_AT						DATETIME2 NULL,
	DELIVERED_CARRIER_DATE			DATETIME2 NULL,
	DELIVERED_CUSTOMER_DATE			DATETIME2 NULL,
	ESTIMATED_DELIVERY_DATE			DATETIME2 NULL
);

CREATE TABLE dbo.TB_ACT_ORDER_ITEMS (
	ORDER_ID						VARCHAR(150),
	PRODUCT_ID						VARCHAR(150),
	SELLER_ID						VARCHAR(150),
	ORDER_ITEM_ID					INT,
	SHIPPING_LIMIT_DATE				DATETIME2,
	PRICE							FLOAT,
	FREIGHT_VALUE					FLOAT
);

CREATE TABLE dbo.TB_ACT_ORDER_PAYMENT (
	ORDER_ID						VARCHAR(150),
	PAYMENT_SEQUENTIAL				INT,
	PAYMENT_TYPE					VARCHAR(40),
	INSTALLMENTS					INT,
	PAYMENT_VALUE					FLOAT
);

CREATE TABLE dbo.TB_ACT_ORDER_REVIEW (
	ID								VARCHAR(150),
	ORDER_ID						VARCHAR(150),
	SCORE							INT,
	COMMENT_TITLE					VARCHAR(256) NULL,
	COMMENT_MESSAGE					TEXT NULL,
	CREATION_DATE					DATE,
	ANSWER_TIMESTAMP				DATETIME2
)